config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  get 'place/index'
  get 'character/index'
  get 'episode/index'
  get 'place/index'
  root to: 'welcome#index'
  get '/search' => 'search#index'
  get 'search/search' => 'search#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/character_controller.rb
class CharacterController < ApplicationController
  def index
    require 'json'
    require 'rest-client'
    @url = "https://integracion-rick-morty-api.herokuapp.com/api/character/#{URI.encode(params[:motivo])}"
    @response = RestClient.get @url
    @result = JSON.parse @response.to_str
  end
end

app/controllers/episode_controller.rb
class EpisodeController < ApplicationController
  def index
    require 'json'
    require 'rest-client'
    @url = "https://integracion-rick-morty-api.herokuapp.com/api/episode/#{URI.encode(params[:motivo])}"
    @response = RestClient.get @url
    @result = JSON.parse @response.to_str
  end

end

app/controllers/place_controller.rb
class PlaceController < ApplicationController
  def index
    require 'json'
    require 'rest-client'
    @url = "https://integracion-rick-morty-api.herokuapp.com/api/location/#{URI.encode(params[:motivo])}"
    @response = RestClient.get @url
    @result = JSON.parse @response.to_str
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    require 'json'
    require 'rest-client'
    @url1 = 'https://integracion-rick-morty-api.herokuapp.com/api/episode'
    @response1 = RestClient.get @url1
    @result1 = JSON.parse @response1.to_str
    @url2 = 'https://integracion-rick-morty-api.herokuapp.com/api/episode?page=2'
    @response2 = RestClient.get @url2
    @result2 = JSON.parse @response2.to_str
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/character_helper.rb
module CharacterHelper
end

app/helpers/episode_helper.rb
module EpisodeHelper
end

app/helpers/place_helper.rb
module PlaceHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/travel_helper.rb
module TravelHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/character/index.html.erb
<h4> <%= link_to 'Volver inicio', root_path %></h4>
<hr>
<div class="container">
  <div class="row">
    <div class="col-lg-12 mt-5">
      <div class="mx-auto mt-5" style="width: 400px">
        <%= form_with(url: search_path, method: 'get', local: true) do %>
          <div class="form-group">
            <%= label_tag :motivo, 'Busqueda '%>
            <%= text_field_tag :motivo, nil, placeholder: 'Ejemplo: Morty', class: 'form-control' %>
          </div>
          <%= button_tag 'Search', class: 'btn btn-success btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
<hr>
<h1> Nombre: <%=@result['name']%></h1>
<hr>
<h3> Estatus: <%=@result['status']%></h3>
<hr>
<h3> Especie: <%=@result['species']%></h3>
<hr>
<h3> Tipo: <%=@result['type']%></h3>
<hr>
<h3> Genero: <%=@result['gender']%></h3>
<hr>

<% @url2 = @result['origin']['url'] %>
<% @response2 = RestClient.get @url2 %>
<% @result2 = JSON.parse @response2.to_str %>
<h2> Origen: <%= link_to @result['origin']['name'], place_index_path(:motivo => @result2['id']) %></h2>

<hr>
<% @url3 = @result['location']['url'] %>
<% @response3 = RestClient.get @url3 %>
<% @result3 = JSON.parse @response3.to_str %>
<h2> Ubicacion: <%= link_to @result['location']['name'], place_index_path(:motivo => @result3['id']) %></h2>

<hr>

<h3> Imagen:</h3>
<img src=<%=@result['image']%>>
<hr>


<h2> Episodios: </h2>
<hr>

<% @result['episode'].each do |episode| %>
    <% @url1 = episode %>
    <% @response1 = RestClient.get @url1 %>
    <% @result1 = JSON.parse @response1.to_str %>
    <h3> - <%= link_to @result1['name'], episode_index_path(:motivo => @result1['id']) %></h3>
<% end %>

app/views/episode/index.html.erb
<h4> <%= link_to 'Volver inicio', root_path %></h4>
<hr>
<div class="container">
  <div class="row">
    <div class="col-lg-12 mt-5">
      <div class="mx-auto mt-5" style="width: 400px">
        <%= form_with(url: search_path, method: 'get', local: true) do %>
          <div class="form-group">
            <%= label_tag :motivo, 'Busqueda '%>
            <%= text_field_tag :motivo, nil, placeholder: 'Ejemplo: Morty', class: 'form-control' %>
          </div>
          <%= button_tag 'Search', class: 'btn btn-success btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
<hr>
<h1> Nombre del episodio: <%=@result['name']%></h1>
<hr>
<h2> Fecha de estreno: <%=@result['air_date']%></h2>
<hr>
<h2> Codigo episodio: <%=@result['episode']%></h2>
<hr>
<h2> Personajes:</h2>
<hr>
<% @result['characters'].each do |character| %>
    <% @url1 = character %>
    <% @response1 = RestClient.get @url1 %>
    <% @result1 = JSON.parse @response1.to_str %>
    <h3> - <%= link_to @result1['name'], character_index_path(:motivo => @result1['id']) %></h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rym</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/place/index.html.erb
<h4> <%= link_to 'Volver inicio', root_path %></h4>
<hr>
<div class="container">
  <div class="row">
    <div class="col-lg-12 mt-5">
      <div class="mx-auto mt-5" style="width: 400px">
        <%= form_with(url: search_path, method: 'get', local: true) do %>
          <div class="form-group">
            <%= label_tag :motivo, 'Busqueda '%>
            <%= text_field_tag :motivo, nil, placeholder: 'Ejemplo: Morty', class: 'form-control' %>
          </div>
          <%= button_tag 'Search', class: 'btn btn-success btn-block' %>
        <% end %>
      </div>
    </div>
  </div>

<hr>
<h1> Nombre: <%=@result['name']%></h1>
<hr>
<h2> Tipo: <%=@result['type']%></h2>
<hr>
<h2> Dimension: <%=@result['dimension']%></h2>
<hr>
<h2> Residentes: </h2>
<hr>
<% @result['residents'].each do |resident| %>
    <% @url1 = resident %>
    <% @response1 = RestClient.get @url1 %>
    <% @result1 = JSON.parse @response1.to_str %>
    <h3> - <%= link_to @result1['name'], character_index_path(:motivo => @result1['id']) %></h3>
<% end %>

app/views/search/index.html.erb
<h4> <%= link_to 'Volver inicio', root_path %></h4>
<hr>

<div class="container">
  <div class="row">
    <div class="col-lg-12 mt-5">
      <div class="mx-auto mt-5" style="width: 400px">
        <%= form_with(url: search_path, method: 'get', local: true) do %>
          <div class="form-group">
            <%= label_tag :motivo, 'Busqueda '%>
            <%= text_field_tag :motivo, nil, placeholder: 'Ejemplo: Morty', class: 'form-control' %>
          </div>
          <%= button_tag 'Search', class: 'btn btn-success btn-block' %>
        <% end %>
      </div>
    </div>
  </div>

<hr>

<h1> Resultados:</h1>

<hr>

<h2> Personajes:</h2>



<hr>

<h2> Episodios:</h2>



<hr>

<h2> Lugares:</h2>


<hr>

app/views/welcome/index.html.erb
<h1>Bienvenido a la app de Rick and Morty</h1>
<p>Por Mario Ogaz</p>

<div class="container">
  <div class="row">
    <div class="col-lg-12 mt-5">
      <div class="mx-auto mt-5" style="width: 400px">
        <%= form_with(url: search_path, method: 'get', local: true) do %>
          <div class="form-group">
            <%= label_tag :motivo, 'Busqueda '%>
            <%= text_field_tag :motivo, nil, placeholder: 'Ejemplo: Morty', class: 'form-control' %>
          </div>
          <%= button_tag 'Search', class: 'btn btn-success btn-block' %>
        <% end %>
      </div>
    </div>
  </div>

<h1>Episodios</h1>
<% @result1['results'].each do |episode| %>
    <hr>
    <h2> Nombre: <%= link_to episode['name'], episode_index_path(:motivo => episode['id'])%></h2>
    <h3> Fecha de transmicion: <%=episode['air_date']%></h3>
    <h3> Codigo episodio: <%=episode['episode']%></h3>
    </hr>
<% end %>

<% @result2['results'].each do |episode| %>
    <hr>
    <h2> Nombre: <%= link_to episode['name'], episode_index_path(:motivo => episode['id'])%></h2>
    <h3> Fecha de transmicion: <%=episode['air_date']%></h3>
    <h3> Codigo episodio: <%=episode['episode']%></h3>
    </hr>
<% end %>